# Generated by Django 5.0.3 on 2024-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='title',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('excited', 'Excited'), ('calm', 'Calm')], max_length=30),
        ),
    ]
