# Generated by Django 5.0.3 on 2024-03-17 20:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracking', '0003_goal_notifications_expense_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='isComplete',
            new_name='isCompleted',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='title',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='value',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_name',
            field=models.CharField(default='limit 200', max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mood',
            name='emoji',
            field=models.CharField(default='/static/images/1', max_length=200),
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_name',
            field=models.CharField(default='happy', max_length=50),
        ),
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mood',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='moodtracking.mood'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mood',
            name='description',
            field=models.CharField(default='this is mood happy', max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
